import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FormProvider } from "react-shadcn-crud-form";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FormProvider
          config={{
            defaultSubmitText: "提交",
            defaultCancelText: "取消",
            defaultShowCancelButton: true,
            validationMode: "onSubmit",
            theme: {
              dialogMaxWidth: "600px",
              dialogMaxHeight: "80vh",
              fieldSpacing: "space-y-6",
            },
          }}
        >
          {children}
        </FormProvider>
      </body>
    </html>
  );
}
